/* Contents autogenerated by dyna_tools.py */
const char *lily_dynaload_table[] = {
    "\0\0"
    ,"F\0next\0(String,Integer):Tuple[String,Integer]"
    ,"F\0size\0(String):Integer"
    ,"F\0readall\0(File):String"
    ,"F\0parse_i\0(String,*Integer):Option[Integer]"
    ,"F\0parse_d\0(String):Option[Double]"
    ,"F\0shell\0(String):String"
    ,"F\0print\0(1...)"
    ,"F\0concat\0(String,1...):String"
    ,"F\0format\0(String,1...):String"
    ,"F\0exit\0(Integer)"
    ,"Z"
};
